// lighting_service.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: lighting_service.proto

package obdservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetHeadlightStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadlightStateRequest) Reset() {
	*x = GetHeadlightStateRequest{}
	mi := &file_lighting_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadlightStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadlightStateRequest) ProtoMessage() {}

func (x *GetHeadlightStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lighting_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadlightStateRequest.ProtoReflect.Descriptor instead.
func (*GetHeadlightStateRequest) Descriptor() ([]byte, []int) {
	return file_lighting_service_proto_rawDescGZIP(), []int{0}
}

type GetHeadlightStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsOn          bool                   `protobuf:"varint,1,opt,name=is_on,json=isOn,proto3" json:"is_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetHeadlightStateResponse) Reset() {
	*x = GetHeadlightStateResponse{}
	mi := &file_lighting_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetHeadlightStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetHeadlightStateResponse) ProtoMessage() {}

func (x *GetHeadlightStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lighting_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetHeadlightStateResponse.ProtoReflect.Descriptor instead.
func (*GetHeadlightStateResponse) Descriptor() ([]byte, []int) {
	return file_lighting_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetHeadlightStateResponse) GetIsOn() bool {
	if x != nil {
		return x.IsOn
	}
	return false
}

type SetHeadlightRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TurnOn        bool                   `protobuf:"varint,1,opt,name=turn_on,json=turnOn,proto3" json:"turn_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHeadlightRequest) Reset() {
	*x = SetHeadlightRequest{}
	mi := &file_lighting_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHeadlightRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeadlightRequest) ProtoMessage() {}

func (x *SetHeadlightRequest) ProtoReflect() protoreflect.Message {
	mi := &file_lighting_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeadlightRequest.ProtoReflect.Descriptor instead.
func (*SetHeadlightRequest) Descriptor() ([]byte, []int) {
	return file_lighting_service_proto_rawDescGZIP(), []int{2}
}

func (x *SetHeadlightRequest) GetTurnOn() bool {
	if x != nil {
		return x.TurnOn
	}
	return false
}

type SetHeadlightResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetHeadlightResponse) Reset() {
	*x = SetHeadlightResponse{}
	mi := &file_lighting_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetHeadlightResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetHeadlightResponse) ProtoMessage() {}

func (x *SetHeadlightResponse) ProtoReflect() protoreflect.Message {
	mi := &file_lighting_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetHeadlightResponse.ProtoReflect.Descriptor instead.
func (*SetHeadlightResponse) Descriptor() ([]byte, []int) {
	return file_lighting_service_proto_rawDescGZIP(), []int{3}
}

func (x *SetHeadlightResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_lighting_service_proto protoreflect.FileDescriptor

const file_lighting_service_proto_rawDesc = "" +
	"\n" +
	"\x16lighting_service.proto\x12\blighting\"\x1a\n" +
	"\x18GetHeadlightStateRequest\"0\n" +
	"\x19GetHeadlightStateResponse\x12\x13\n" +
	"\x05is_on\x18\x01 \x01(\bR\x04isOn\".\n" +
	"\x13SetHeadlightRequest\x12\x17\n" +
	"\aturn_on\x18\x01 \x01(\bR\x06turnOn\"0\n" +
	"\x14SetHeadlightResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xc2\x01\n" +
	"\x0fLightingService\x12^\n" +
	"\x11GetHeadlightState\x12\".lighting.GetHeadlightStateRequest\x1a#.lighting.GetHeadlightStateResponse\"\x00\x12O\n" +
	"\fSetHeadlight\x12\x1d.lighting.SetHeadlightRequest\x1a\x1e.lighting.SetHeadlightResponse\"\x00B&Z$github.com/halldorstefans/obdserviceb\x06proto3"

var (
	file_lighting_service_proto_rawDescOnce sync.Once
	file_lighting_service_proto_rawDescData []byte
)

func file_lighting_service_proto_rawDescGZIP() []byte {
	file_lighting_service_proto_rawDescOnce.Do(func() {
		file_lighting_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_lighting_service_proto_rawDesc), len(file_lighting_service_proto_rawDesc)))
	})
	return file_lighting_service_proto_rawDescData
}

var file_lighting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_lighting_service_proto_goTypes = []any{
	(*GetHeadlightStateRequest)(nil),  // 0: lighting.GetHeadlightStateRequest
	(*GetHeadlightStateResponse)(nil), // 1: lighting.GetHeadlightStateResponse
	(*SetHeadlightRequest)(nil),       // 2: lighting.SetHeadlightRequest
	(*SetHeadlightResponse)(nil),      // 3: lighting.SetHeadlightResponse
}
var file_lighting_service_proto_depIdxs = []int32{
	0, // 0: lighting.LightingService.GetHeadlightState:input_type -> lighting.GetHeadlightStateRequest
	2, // 1: lighting.LightingService.SetHeadlight:input_type -> lighting.SetHeadlightRequest
	1, // 2: lighting.LightingService.GetHeadlightState:output_type -> lighting.GetHeadlightStateResponse
	3, // 3: lighting.LightingService.SetHeadlight:output_type -> lighting.SetHeadlightResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_lighting_service_proto_init() }
func file_lighting_service_proto_init() {
	if File_lighting_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_lighting_service_proto_rawDesc), len(file_lighting_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_lighting_service_proto_goTypes,
		DependencyIndexes: file_lighting_service_proto_depIdxs,
		MessageInfos:      file_lighting_service_proto_msgTypes,
	}.Build()
	File_lighting_service_proto = out.File
	file_lighting_service_proto_goTypes = nil
	file_lighting_service_proto_depIdxs = nil
}
