// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.12.4
// source: obd_service.proto

package obdservice

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// The request message for getting fuel level
type FuelLevelRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Any additional parameters can be added here
	// For example, vehicle identification, etc.
	VehicleId     string `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuelLevelRequest) Reset() {
	*x = FuelLevelRequest{}
	mi := &file_obd_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelLevelRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelLevelRequest) ProtoMessage() {}

func (x *FuelLevelRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelLevelRequest.ProtoReflect.Descriptor instead.
func (*FuelLevelRequest) Descriptor() ([]byte, []int) {
	return file_obd_service_proto_rawDescGZIP(), []int{0}
}

func (x *FuelLevelRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

// Request for streaming fuel level updates
type FuelLevelStreamRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	VehicleId string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	// Interval in seconds between updates
	IntervalSeconds uint32 `protobuf:"varint,2,opt,name=interval_seconds,json=intervalSeconds,proto3" json:"interval_seconds,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *FuelLevelStreamRequest) Reset() {
	*x = FuelLevelStreamRequest{}
	mi := &file_obd_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelLevelStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelLevelStreamRequest) ProtoMessage() {}

func (x *FuelLevelStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_obd_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelLevelStreamRequest.ProtoReflect.Descriptor instead.
func (*FuelLevelStreamRequest) Descriptor() ([]byte, []int) {
	return file_obd_service_proto_rawDescGZIP(), []int{1}
}

func (x *FuelLevelStreamRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *FuelLevelStreamRequest) GetIntervalSeconds() uint32 {
	if x != nil {
		return x.IntervalSeconds
	}
	return 0
}

// The response message containing the fuel level
type FuelLevelResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Fuel level in percent (0.0 - 100.0)
	LevelPercent float32 `protobuf:"fixed32,1,opt,name=level_percent,json=levelPercent,proto3" json:"level_percent,omitempty"`
	// Timestamp of the reading (in milliseconds since epoch)
	TimestampMs uint64 `protobuf:"varint,2,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Status code (0 = OK, non-zero = error)
	Status int32 `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	// Optional error message if status is non-zero
	ErrorMessage  string `protobuf:"bytes,4,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FuelLevelResponse) Reset() {
	*x = FuelLevelResponse{}
	mi := &file_obd_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FuelLevelResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FuelLevelResponse) ProtoMessage() {}

func (x *FuelLevelResponse) ProtoReflect() protoreflect.Message {
	mi := &file_obd_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FuelLevelResponse.ProtoReflect.Descriptor instead.
func (*FuelLevelResponse) Descriptor() ([]byte, []int) {
	return file_obd_service_proto_rawDescGZIP(), []int{2}
}

func (x *FuelLevelResponse) GetLevelPercent() float32 {
	if x != nil {
		return x.LevelPercent
	}
	return 0
}

func (x *FuelLevelResponse) GetTimestampMs() uint64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *FuelLevelResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *FuelLevelResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_obd_service_proto protoreflect.FileDescriptor

const file_obd_service_proto_rawDesc = "" +
	"\n" +
	"\x11obd_service.proto\x12\x03obd\"1\n" +
	"\x10FuelLevelRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\"b\n" +
	"\x16FuelLevelStreamRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12)\n" +
	"\x10interval_seconds\x18\x02 \x01(\rR\x0fintervalSeconds\"\x98\x01\n" +
	"\x11FuelLevelResponse\x12#\n" +
	"\rlevel_percent\x18\x01 \x01(\x02R\flevelPercent\x12!\n" +
	"\ftimestamp_ms\x18\x02 \x01(\x04R\vtimestampMs\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\x12#\n" +
	"\rerror_message\x18\x04 \x01(\tR\ferrorMessage2\x99\x01\n" +
	"\n" +
	"OBDService\x12?\n" +
	"\fGetFuelLevel\x12\x15.obd.FuelLevelRequest\x1a\x16.obd.FuelLevelResponse\"\x00\x12J\n" +
	"\x0fStreamFuelLevel\x12\x1b.obd.FuelLevelStreamRequest\x1a\x16.obd.FuelLevelResponse\"\x000\x01B&Z$github.com/halldorstefans/obdserviceb\x06proto3"

var (
	file_obd_service_proto_rawDescOnce sync.Once
	file_obd_service_proto_rawDescData []byte
)

func file_obd_service_proto_rawDescGZIP() []byte {
	file_obd_service_proto_rawDescOnce.Do(func() {
		file_obd_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_obd_service_proto_rawDesc), len(file_obd_service_proto_rawDesc)))
	})
	return file_obd_service_proto_rawDescData
}

var file_obd_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_obd_service_proto_goTypes = []any{
	(*FuelLevelRequest)(nil),       // 0: obd.FuelLevelRequest
	(*FuelLevelStreamRequest)(nil), // 1: obd.FuelLevelStreamRequest
	(*FuelLevelResponse)(nil),      // 2: obd.FuelLevelResponse
}
var file_obd_service_proto_depIdxs = []int32{
	0, // 0: obd.OBDService.GetFuelLevel:input_type -> obd.FuelLevelRequest
	1, // 1: obd.OBDService.StreamFuelLevel:input_type -> obd.FuelLevelStreamRequest
	2, // 2: obd.OBDService.GetFuelLevel:output_type -> obd.FuelLevelResponse
	2, // 3: obd.OBDService.StreamFuelLevel:output_type -> obd.FuelLevelResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_obd_service_proto_init() }
func file_obd_service_proto_init() {
	if File_obd_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_obd_service_proto_rawDesc), len(file_obd_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_obd_service_proto_goTypes,
		DependencyIndexes: file_obd_service_proto_depIdxs,
		MessageInfos:      file_obd_service_proto_msgTypes,
	}.Build()
	File_obd_service_proto = out.File
	file_obd_service_proto_goTypes = nil
	file_obd_service_proto_depIdxs = nil
}
